[project]
name = "Python_basics_uv"
version = "0.0.0"
requires-python = ">=3.12"
dependencies = [
    "ipykernel",
    "ipython",
    "matplotlib",
    "numpy",
    "openpyxl",
    "pandas",
    "pip",
    "pyarrow",
    "scipy",
]

[tool.uv]
dev-dependencies = []
